# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Martin Biel
tagline:          'Personal webpage'
description:      '<p> Ph.D Student</p> <p> Department of Automatic Control </p> <p> KTH Royal Institute of Technology </p>'
google_analytics: UA-84669373-1
url:              localhost:4000
baseurl:          /

author:
  name:           'Martin Biel'

paginate:         5

# Custom vars
version:          2.1.0
markdown:         kramdown

gems:		  [jekyll-paginate, jekyll-gist, redcarpet, jekyll-sitemap, kramdown]

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

collections:
    publications:
        output: true
    teachingmaterial:
